spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  docker:
    compose:
      file: "E:/ЮМШ/Projects/OlympTaskSetter/olymp-task-setter/docker-compose.local.yml"

